### ISSUE TITLE
消耗CPU特别厉害

### ISSUE THREAD

**Issue by Heisenbean** [CoderJee/DRNRealTimeBlurView#1]
你好,最近在用您这的这个做一个毛玻璃效果,但是发现十分耗CPU,不知道您试过没有,令我在我的项目里还会报一个CGContextSetBaseCTM的错误.

**Comment by CoderJee** [comment]
此毛玻璃只适用于静态页面，动态页面会很卡(可滑动界面),目前还没发现可滑动的效果好的毛玻璃效果(除了苹果iOS8原生自带的UIBlurEffect),至于报错，上截图。

**Comment by Heisenbean** [comment]
现在解决了,麻烦你了..可以close这个issue了~
